### ISSUE TITLE
VR mode orientation bug

### ISSUE THREAD

**Issue by seankovacs** [googlevr/gvr-ios-sdk#128]
When going into VR mode, the directions only clear when going from portrait to landscape RIGHT. 

Starting in landscape, either RIGHT or LEFT, the directions still show (bug also IMO), and are force 
to go from portrait to landscape RIGHT to get it to hide and show the cardboard VR view. Going from portrait to landscape LEFT doesn't hide the directions.

So two bugs:
1) Directions only hide when going to landscape RIGHT, ignoring landscape LEFT.
2) Starting in landscape mode, the directions still appear.

**Comment by nathanmartz** [comment]
These are actually both by design. Right now various parts of our SDK only support landscape right. The message shows when you start in landscape because users still need to understand that they need to put the phone into a viewer (a thing many people do not understand). In this case it goes away on a timer.
