### ISSUE TITLE
Could the GVRAudioEngine of Ambisonic soundfields type support audio streaming  or AAC?

### ISSUE THREAD

**Issue by lianguowu** [googlevr/gvr-ios-sdk#151]
I just find the func :- (int)createSoundfield:(const NSString*)filename;, I want get the streaming of Ambisonic audio to play , could the GVRAudioEngine accomplish it？and I want to play the   Ambisonic audio of AAC type.

**Comment by jkammerl** [comment]
The GVRAudioEngine decodes compressed audio files by using the iOS media stack and unfortunately some iPhones don't seem to properly support multichannel decoding of AAC content.   This issue is on our radar and we are currently considering integrating a software decoder into GVR to be independent from Apple's audio codec support.
