### ISSUE TITLE
Support for HLS streaming in GVRVideoView

### ISSUE THREAD

**Issue by jietan** [googlevr/gvr-ios-sdk#167]
HLS is a popular live streaming protocol. It is supported in the Google VR SDK for Android. Is it currently supported in GVRVideoView for IOS? If not, is there any plan to add in this feature? Thanks.

**Comment by nathanmartz** [comment]
We support HLS on both Android and iOS.

**Comment by MatejBalantic** [comment]
@nathanmartz HLS remote streaming does not work for us either. It starts the video momentarily but then soon freezes and stops playback. The same HLS stream works just fine with vanilla AVPlayerViewController.  

I am trying to get the sample video to share here (can't share the original due to contractual obligation) but there is definitely something wrong with HLS. Streaming the mp4 works fine.
