### ISSUE TITLE
VR display mode show black screen if I alloc more than two GVRVideoView

### ISSUE THREAD

**Issue by huynguyencong** [googlevr/gvr-ios-sdk#182]
I create an application, that have a `UIPageViewController`. In each page, I add a `GVRVideoView`. When user scroll to a page, I pause video of previous page and play video in new page. But just first page can play correctly in VR Mode. Others page show black screen.

I'm using version 1.10.0

![Black screen](https://monosnap.com/file/WDTLHzAOkh49nLPKA8md7rLnLCCE72.png)

**Comment by sanjayc77** [comment]
Thanks for reporting. Added to internal tracker.

**Comment by huynguyencong** [comment]
The problem is: Not be able to exist more than one GVRVideoView instance in an app. I have to cheat by put it into a singleton, and remove it from previous page, add to new page when user scroll UIPageViewController. But it isn't convinient.

**Comment by sanjayc77** [comment]
Is this happening with 1.20.0 version?

**Comment by keakalamudo** [comment]
I am still experiencing this on version 1.20.0

**Comment by abhi2015** [comment]
@sanjayc77 Any updates on this fix?

**Comment by abhi2015** [comment]
The issue still persists with 1.20.0 @sanjayc77 @dav-cz

**Comment by tibewww** [comment]
I'm experiencing the same problem !

Weird, sometime it does play the sound, but not the video !

Did you find any solutions ?

Thanks :)

**Comment by ashishbitcot** [comment]
GVRVideoView doesn't show video in cardboard mode and just the black screen, though the audio plays. Can I know what could be the issue. Am using the same code as in the standard VideoWidgetDemo of GoogleVRSDK, just that I have converted it to swift equivalent.

Note: Using GVRSDK 1.10.0

When using higher versions, the video shows but because it is unstable and has lot of issues, specially the stalled playback on buffering, I opted to use 1.10.0, as used in the standard Google example.

Please help, thanks in advance.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
