### ISSUE TITLE
can not package my ipa.

### ISSUE THREAD

**Issue by SnowMusic** [googlevr/gvr-ios-sdk#184]
when i package my project, i miss "missing required architecture arm64" bug.and my xcode version is 8.2.1.how to solved it ?

**Comment by sanjayc77** [comment]
Is this happening with the sample apps as well? https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples

We supply cocoapod libraries as separated architectures. You can try to combine then into one fat universal library using lipo:

lipo -create libGVRSDK_x86_64.a libGVRSDK_i386.a libGVRSDK_armv7.a libGVRSDK_arm64.a -output libGVRSDK.a

You will also have to adjust the linker flags to only reference the fat lib.


Or you can wait for the next release (soon). We will provide the fat lib instead of individual arch libs.
