### ISSUE TITLE
libGVRSDK.a is massive

### ISSUE THREAD

**Issue by ghking** [googlevr/gvr-ios-sdk#202]
libGVRSDK.a is 118.5 MB after running `pod install`. GitHub's file size limit is 100 MB.

My team follows [CocoaPod's recommendation](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control) of checking in the `Pods` directory, so we're not able to upgrade to 1.20.0 with a file of this size.

It would be awesome if this could be reduced in some way. Thanks!

**Comment by sanjayc77** [comment]
You will not like the answer, the size will only go up:

1. We consolidated the three subspecs: GVRView, GVRSDK and GVRSDK back into just GVRSDK in 1.20.0 release.
2. The library, libGVRSDK.a, contains 4 architectures: i386, x86_64, armv7 and arm64.
3. We added bitcode support, that balloons the size of the library significantly. Unfortunately, the bitcode was enabled partially, an issue we are rectifying in the next release. When enabled completely, the size will only go up.

I would recommend, not checking in the library to GitHub. Even Cocoapod does not store the binary on GitHub, it is pulled from Google's servers at the time of pod install.

We could look into breaking the library in simulator vs. device (i386, x86_64 vs armv7, arm64) or dropping older architectures: i386 and armv7. But these may not help you considering the addition due to bitcode.
