### ISSUE TITLE
Indication of stalled playback due to running out of buffered video

### ISSUE THREAD

**Issue by ghking** [googlevr/gvr-ios-sdk#206]
Currently, there is no way to know if the video has paused due to running out of buffered video. It would be great if there was an observable property or delegate method to expose this situation so the UI could react to it.

**Comment by ashishbitcot** [comment]
GVRVideoView doesn't show video in cardboard mode and just the black screen, though the audio plays. Can I know what could be the issue. Am using the same code as in the standard VideoWidgetDemo of GoogleVRSDK, just that I have converted it to swift equivalent.

Note: Using GVRSDK 1.10.0

When using higher versions, the video shows but because it is unstable and has lot of issues, specially the stalled playback on buffering, I opted to use 1.10.0, as used in the standard Google example.

Please help, thanks in advance.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
