### ISSUE TITLE
Play video in stereo ?

### ISSUE THREAD

**Issue by tibewww** [googlevr/gvr-ios-sdk#214]
Hi guys,

I'm trying to read video in a stereo mode .. 

without success unfortunately.

Below is my code:

`
        
        videoVRView.enableCardboardButton = true
        videoVRView.enableFullscreenButton = true
        videoVRView.delegate = self
    videoVRView.GVRWidgetdisplayMode = GVRWidgetDisplayMode.fullscreenVR
videoVRView.load(from: URL(string: "\(posts[selectedIndexPath].link)"))
`

Which works for monovideo.

I trie to add the following instead:

`      videoVRView.load(from: URL(string: "\(posts[selectedIndexPath].link)"), ofType: kGVRVideoTypeStereoOverUnder)
`

But i'm getting a 'User of unresolved identifier kGVRVideoTypeStereoOverUnder''

Any idea how we can make this work ? It's all running in swift 3.0...

Thanks a lot for your help !!

**Comment by tibewww** [comment]
I got it via :

`       videoVRView.load(from: URL(string: "\(posts[selectedIndexPath].link)"), of: GVRVideoType.stereoOverUnder
`

Otherwise is  there a way to have a if statement and recognize if the video is in stereo start the stereomode and if not play it in mono ??

**Comment by ashishbitcot** [comment]
GVRVideoView doesn't show video in cardboard mode and just the black screen, though the audio plays. Can I know what could be the issue. Am using the same code as in the standard VideoWidgetDemo of GoogleVRSDK, just that I have converted it to swift equivalent.

Note: Using GVRSDK 1.10.0

When using higher versions, the video shows but because it is unstable and has lot of issues, specially the stalled playback on buffering, I opted to use 1.10.0, as used in the standard Google example.

Please help, thanks in advance.

**Comment by sanjayc77** [comment]
GVRView API (that includes GVRVideoView) is now deprecated. Please switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). It is also available as a Cocoapod. Take a look at the updated VideoWidgetDemo sample app.
