### ISSUE TITLE
1.1.0 is not work HLS stream in iOS 10.2 or lower version

### ISSUE THREAD

**Issue by younatics** [googlevr/gvr-ios-sdk#251]
Hello, 
I found HLS stream is not work well in iOS 10.2 or lower version.  
This is test url (http://v.zigbang.com/360/14029/main/master.m3u8)
If I rollbacked to 0.9.0 version, It works fine. 
please fix this issue.

Regards,
younatics

**Comment by sanjayc77** [comment]
This does not load in AVPlayer: "Failed to load video: Cannot Parse"
GVRVideoView uses AVPlayer internally. Does this load in AVPlayer outside of GVRVideoView?

**Comment by younatics** [comment]
Hello @sanjayc77,
In iOS 10.3 or higher version, I can play HLS stream. 
Is there any difference between this version?

Thanks,

**Comment by younatics** [comment]
https://github.com/younatics/avplayer-sample
You can see that I can play in Avplayer without GVRVideoView

**Comment by khanhlvg** [comment]
Hi @sanjayc77 

The issue we are seeing here is that this 360 video (http://v.zigbang.com/360/14029/main/master.m3u8) plays well on iOS 10.3, but not on iOS 10.0 to iOS 10.2. GVRSDK 1.60.0 (latest) is used.

Could you look into what caused the problem? You can reproduce using iOS Simulator.

**iOS 10.0 to 10.2**
![simulator screen shot may 25 2017 11 18 10 am](https://cloud.githubusercontent.com/assets/5379361/26433847/f88460c2-413f-11e7-9952-7ecaa07d54da.png)

**iOS 10.3**
![simulator screen shot may 25 2017 11 18 48 am](https://cloud.githubusercontent.com/assets/5379361/26433851/fcbf62fe-413f-11e7-9c1a-2b5488d19584.png)

**Comment by younatics** [comment]
Thanks! @khanhlvg :)

**Comment by sanjayc77** [comment]
I was able to playback the video on 10.3.1 on the VideoPlayer sample app after adding App Transport Security Key to Info.plist (since the Url begins with http). It also worked on the iPhone simulator (9.0 and 10.3), but not on 10.2. I think this might be a bug in iOS: https://forums.developer.apple.com/thread/67268

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
</plist>

**Comment by younatics** [comment]
Hello, @sanjayc77 
Thank you for your reply. 
However, I can play hls stream in iOS 10.2 when I use 0.9.0 GVR version. 
Is there any difference between 0.9.0 version and 1.1 or higher version?
