### ISSUE TITLE
[Unity 2017.1.0f3 - iOS] Black Screen When Using VR Mode

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-ios-sdk#271]
Cross listing this issue here since I believe it's likely more of an iOS GVR SDK bug vs. Unity GVR SDK bug as I don't actually have the Unity GVR SDK installed and I can still replicate this.

https://github.com/googlevr/gvr-unity-sdk/issues/661
https://issuetracker.unity3d.com/issues/ios-cardboard-opengles-black-screen-on-vr-cardboard-builds-with-opengles2

**Comment by dustinkerstein** [comment]
FYI - This is still reproducible on Unity 2017.1.1p3 and the current 2017.2 beta

**Comment by fredsa** [comment]
Dustin, do you any additional details which might help us track down this issue?

I'm not able to reproduce the black screen. I just tried building a default project using both Unity 2017.1.1f1 and 2017.1.1p3. Both apps run correctly on an iOS 11.0 phone (A1687 - iPhone 6S Plus).

The only Unity settings I changed were:
* **Player Settings > iOS > Virtual Reality Supported**: enabled
* **Player Settings > iOS > Virtual Reality SDKs > cardboard**
* **Player Settings > iOS > Target minimum iOS Version**: 8.0 (was 7.0 by default)

**Comment by dustinkerstein** [comment]
Interesting. Try with the "None" device loaded first and then load the
"cardboard" device after startup. I'll try to replicate on a simple project
tomorrow morning, but that might be the trick.

**Comment by fredsa** [comment]
Thanks again, Dustin. It seems **Metal** was set as the default Graphics API for me, which is why I wasn't seeing the issue.

I was able to reproduce the black screen by setting either **OpenGLES2** or **OpenGLES3** as the first Graphics API:
* **Player Settings > iOS > Other Settings > Auto graphics API**: disabled
* **Player Settings > iOS > Other Settings > Graphics APIs**: OpenGLES2/3, …

**Comment by fredsa** [comment]
The Google VR SDK for iOS
