### ISSUE TITLE
cardboard settings like distortion enabed missing

### ISSUE THREAD

**Issue by mjsibbald** [googlevr/gvr-ios-sdk#3]
Love this ios version, but the only setting we have is the VR mode. Is there a way to turn of distortion of vignette etc...?

**Comment by nathanmartz** [comment]
What are you trying to do? For stereo, distortion correction is critical, so would like to understand why you want to disable it. Also, the VR View elements support full screen monoscopic.

**Comment by mjsibbald** [comment]
Als a developer I would like to have the freedom to develop part of these
features myself. As for the distortion, we had this freedom on the android
and unity sdk. I know it critical, but for developers it leaves no room for
custom work.

Besides distortion non of the others are available as well.

Still appreciate google is taking the effort building a objective-c
version. And it would help a lot of developers that implement the default
functionality.

-- 
Maikel Sibbald

**Comment by nathanmartz** [comment]
Hi. Thanks for the feedback. I've added a task in our tracker for this and expect it to be included in our next proper release (1-2 months).

**Comment by mjsibbald** [comment]
Hey Nathan,

Thank you so much. Any ETA on this. Would be very appreciated.

**Comment by nathanmartz** [comment]
Hi. After discussing this intensively internally, we've decided that we will not be adding optional distortion to the iOS SDK. It adds quite a bit of complexity to the underlying code, and we're seriously considering deprecating that option in Android and Unity, too.

We're still discussing the best way to support some of your other requests, like customizing the look of various UI elements.

**Comment by mjsibbald** [comment]
I would recommend making this optional because the current solution drops frames in Android. As far as I can tell its a 2 pass shader solution? There are multiple reports on people having their frames dropped. So giving developer the chance to write their own distortion based on the one that is shown in the Google Cardboard Design lab. Not making this optional is a limitation for some developers. My 2 cents

**Comment by kaztorama** [comment]
Hi @mjsibbald 
I started using vertex displacement for VR Distortion Correction in my VR apps since I saw the Brian's [video](https://www.youtube.com/watch?v=yJVkdsZc9YA) on Google I/O 2016. The advantages are really worth it. I have a samsung s6 and without this method it will get really hot really fast and the frame rate will start dropping immediately. Unfortunately now it's a real pain to set it up with the latest versions of Unity and GVR. I wonder if you are still pursuing this or if you already gave up on it?

I've been doing some tests since friday with different versions of Unity combined with different versions of Cardboard and GVR and for now the best results I was able to achieve were using the old Cardboard SDK (the same used in Google Cardboard Design Lab) and Unity 5.6 (5.6.0f3). I enabled Virtual Reality Supported with the Split Stereo Screen SDK.

It's a shame I don't see more people on the internet using this method. Should we try to create some kind of awareness for this issue to see if we get enough developers pushing for it?
