### ISSUE TITLE
Create Hotspot Panoroma Image

### ISSUE THREAD

**Issue by anks62** [googlevr/gvr-ios-sdk#79]
Hi @nathanmartz I hope you are fine and doing great work.

Let me tell How i create many hotspots and excute hotspots click event in panoroma image.

For Ex 
if Image size is 3000X320 , I want to create one hotspot at (100,200) position, second hotspot at (1300,200) position, third hotspot at (2800,200) position
so initially i can see second hotspot in device display and when i moved my phone on left side, i  can see first hotspot.  when i moved my phone on Right side, i can see third hotspot.

Can i move Panoroam image with touch event means without moving of devicce ?

Thanks

@nathanmartz

**Comment by nathanmartz** [comment]
Hi. There are two separate requests here. In terms of moving the image via touch instead of via device movement, that's something we definitely plan on doing.

Regarding adding hotspots, that's something we've discussed but it's not officially on our roadmap right now. You can add that support yourself, especially if you use the lower level GVRView and related classes.

**Comment by anks62** [comment]
Thanks, @nathanmartz for your co operations and reply.
I am waitting and eagerness to see above two features or may be  in next version
